Add Write overloads with return value
realm/realm-dotnet pull request #2082
Opened 2020-10-23 12:56 UTC by papafe

## Description

This is a work in progress PR that add new overloads for `Write` and `WriteAsync` methods, so that they can return a value. 

Fixes #2081 

##  TODO

* [ ] Changelog entry
* [ ] Tests (if applicable)

2020-10-23 15:02 UTC, nirinchev reviewed
Looks good - just a few documentation nits from me + a request to deduplicate the code in the existing Write method.

2020-10-23 15:02 UTC, nirinchev commented on Realm/Realm/Realm.cs
>              transaction.Commit();
Can we implement this `Write` in terms of the new one? I know it's a fairly trivial method, but the less code we have, the less bugs we'll ship 😄

2020-10-26 08:34 UTC, papafe commented on Realm/Realm/Realm.cs
> +        /// Delegate with one return value to perform inside a <see cref="Transaction"/>, creating, updating or removing objects.
> `perform` -> `execute`?

Regarding this and the following comment, I have copied almost verbatim the documentation for the plain `Write`, so I'll correct both of them there too. 
I'm not a fan of the Oxford comma actually, but let's agree on doing it ;)

2020-10-26 09:50 UTC, nirinchev commented on Realm/Realm/Realm.cs
> +        /// Delegate with one return value to perform inside a <see cref="Transaction"/>, creating, updating or removing objects.
Yeah, I'm guessing the person who wrote the docs for the original `Write` method felt that "perform an action" makes sense and it kinda does, although I still think "execute" is better. But "perform a delegate" is awkward. So yeah, let's change in both places.

2020-10-26 11:17 UTC, papafe commented
I have corrected the documentation and modified the old `Write` method to use the new one, and it seems that the tests are still fine.

I think that the test cases specifically for the new function need to be moved to a new test class, as it seems that there is none of the current ones is related to this. At the moment the tests are in the `AddOrUpdateTests` just for convenience.

2020-10-26 12:08 UTC, nirinchev commented
The CI test failures are legitimate - the `Compact_ShouldReduceSize` are flaky and you can ignore them, but `Realms.Tests.Database.DynamicRelationshipTests` are legitimate failures and need to be fixed. My hunch is that the binder is mistakenly using the new `Write(Func<T>)` overload instead of the old `Write(Action)` one, so we might need to be more explicit about which overload to use.

2020-10-26 13:40 UTC, papafe commented
Yes, it was actually using the new `Write(Func<T>` instead of the old one. This can be easily fixed, but made me realise that this is actually true for all cases in which the input value of `Write` is an expression lambda (that returns something else than void) instead of a statement lambda.

2020-10-26 20:34 UTC, nirinchev approved these changes
Nice job!

2020-11-03 19:09 UTC, nirinchev requested changes
Looking solid, but I think there are some areas where we can simplify the code a little.

2020-11-03 19:09 UTC, nirinchev commented on Realm/Realm/Realm.cs
> +            else
Perhaps also invert the if clause to do an early return and reduce the nesting of the majority of the method:

```csharp
if (! AsyncHelper.HasValidContext)
{
    return Task.FromREsult(Write(() => function(this)));
}

async Task<T> DoWorkAsync()
{
    // ...
}

return DoWork();
```

2020-11-03 19:09 UTC, nirinchev commented on Realm/Realm/Realm.cs
> +        /// await realm.WriteAsync(tempRealm =&gt;
Perhaps add `var dogs = await realm.WriteAsync...`

2020-11-03 19:09 UTC, nirinchev commented on Realm/Realm/Realm.cs
> +        public Task<IList<T>> WriteAsync<T>(Func<Realm, IList<T>> function)
The comments for the `IQueryable` overload apply to this one too.

2020-11-03 19:09 UTC, nirinchev commented on Tests/Realm.Tests/Database/WriteOverloads.cs
> +    public class WriteOverloads : RealmInstanceTest
Perhaps it's worth adding a test that ensures that an exception is thrown if the user returns a managed object/query/list indirectly, e.g.:

```csharp
var temp = await _realm.WriteAsync(bgRealm =>
{
    var obj = bgRealm.Add(new IntPrimaryKeyWithValueObject());
    return new
    {
        ManagedObject = obj,
        SomeValue = 123
    };
});

Assert.Throws<*not-sure-what-exception*>(() => temp.ManagedObject.Id);
```

2020-11-04 10:38 UTC, papafe commented on Tests/Realm.Tests/Realm.Tests.csproj
> +    <Compile Update="Database\WriteOverloads.cs">
I'll remove it

2020-11-04 11:33 UTC, papafe commented
- Added new test case for managed objects returned indirectly
- Changed a little bit documentation to make it clearer that methods return a value
- Refactored code to remove unnecessary `else`
- Simplified code of `WriteAsync`

2020-11-04 11:37 UTC, nirinchev approved these changes
Nice job!

2020-11-04 12:26 UTC, nirinchev commented on CHANGELOG.md
> +* Added overloads for `Realm.Write` and `Realm.WriteAsync` that can return a value. (Issue [#2081 (https://github.com/realm/realm-dotnet/issues/2081)])
```suggestion
* Added overloads for `Realm.Write` and `Realm.WriteAsync` that can return a value. (Issue [#2081](https://github.com/realm/realm-dotnet/issues/2081))
```

2020-11-04 12:27 UTC, nirinchev commented
The failing tests are flaky, so feel free to ignore them.

2020-11-04 13:42 UTC, merged