Move all realm.io links to mongodb docs
realm/realm-dotnet pull request #2249
Opened 2021-02-15 13:11 UTC by LaPeste

## Description
Move all realm.io links to mongodb docs

Fixes #2143 

##  TODO
* [ ] Changelog entry  --> I don't believe there's anything to write

2021-02-15 14:05 UTC, nirinchev requested changes

2021-02-15 14:05 UTC, nirinchev commented on Realm/Realm/Schema/RealmSchema.cs
> +                        "No RealmObjects. Has linker stripped them? See https://thereIsntSuchDocYet");
Feel free to link to the legacy docs and open a ticket for the team to move the information to the new docs.

2021-02-15 14:05 UTC, nirinchev commented on SUPPORT.md
> +Before asking questions, please familiarize yourself with our [.NET SDK](https://docs.mongodb.com/realm/dotnet/) documentation. We also have a number of [Tech Notes](https://IDontThinkThisExists) whi
Remove the tech notes sentence - we don't have those currently.

2021-02-15 15:52 UTC, LaPeste commented on README.md
> +* **Simple:** Data is directly [exposed as objects](https://docs.mongodb.com/realm/dotnet/objects/) and [queryable by code](https://docs.mongodb.com/realm/dotnet/query-engine/), removing the need for
Maybe that should be reflected also in "The main classes you will use are" section (4th line) in the documentation? ==> https://docs.mongodb.com/realm-sdks/dotnet/latest/

2021-02-15 16:25 UTC, LaPeste commented on Realm/Realm.Unity/package.json
> -      "email": "help@realm.io",
I'm waiting for the email. But only Brian knows and he's in holiday, but we expect to have one soon (2/3 days max).

2021-02-15 21:25 UTC, nirinchev commented on README.md
> +* **Simple:** Data is directly [exposed as objects](https://docs.mongodb.com/realm/dotnet/objects/) and [queryable by code](https://docs.mongodb.com/realm/dotnet/query-engine/), removing the need for
We should completely replace/rewrite that one, just haven't had the time to look into it.

2021-02-15 21:26 UTC, nirinchev commented on Realm/Realm.Unity/package.json
> -      "email": "help@realm.io",
You can also ping Sergey. As far as I remember, help@realm.io also works, just wondering if there's a better one to use.

2021-02-15 21:38 UTC, bmunkholm commented on Realm/Realm.Unity/package.json
> -      "email": "help@realm.io",
realm-help@mongodb.com

2021-02-15 21:56 UTC, nirinchev commented on Realm/Realm.Unity/package.json
> -      "email": "help@realm.io",
Brian, go build a snowman or something 😛 I explicitly didn't tag you so as not to disturb your vacationing!

Appreciate the help though 🙇‍♂️

2021-02-16 15:29 UTC, nirinchev approved these changes

2021-02-16 15:49 UTC, merged