Jg/transaction state
realm/realm-dotnet pull request #3104
Opened 2022-11-21 16:11 UTC by JacobOscarGunnarsson

## Description
Allows a user to check the state of a transaction so it doesn't mistakenly commit/rollback twice

Fixes #2551

2022-11-21 16:12 UTC, JacobOscarGunnarsson commented on Tests/Realm.Tests/Database/InstanceTests.cs
Not entirely sure if this is the correct place to put the test

2022-11-22 09:09 UTC, papafe requested changes

2022-11-22 09:10 UTC, papafe commented
You should also check the CI ;) 
If something is not clear we can talk about it! The UI is a little messy

2022-11-22 10:53 UTC, nirinchev commented on Realm/Realm/Transaction.cs
> +    [Flags]
This should probably not be flags - MS has pretty good docs about what `[Flags]` designates and when to use it [here](https://learn.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-7.0).

2022-11-22 14:02 UTC, nirinchev commented on Realm/Realm/Transaction.cs
>              FinishTransaction();
We can probably move setting the state to `FinishTransaction` and then pass the value as an argument. Not saving a whole lot of code, but it's a bit more expressive as "this is the final thing we need to do as we close out the transaction".

2022-11-22 14:02 UTC, nirinchev commented on Realm/Realm/Transaction.cs
> +        /// <summary>
Spacing seems off here.

2022-11-23 10:52 UTC, LaPeste requested changes
Just some very minor details. Otherwise, the work loos fine.

2022-11-23 10:52 UTC, LaPeste commented on CHANGELOG.md
> +* Added a field `Transaction.State` which describes the current state of the transaction.
```suggestion
* Added a field `Transaction.State` which describes the current state of the transaction. (Issue [#2551](https://github.com/realm/realm-dotnet/issues/2551)
```

2022-11-24 12:41 UTC, papafe commented
Looks good! I would just add one test, to verify that it works also for `CommitAsync` and then if the CI agrees, it's good to go ;)

2022-11-24 17:36 UTC, merged