Add support for nested classes in source generator
realm/realm-dotnet pull request #3151
Opened 2023-01-05 15:03 UTC by papafe

Fixes #3031 

##  TODO

* [ ] Changelog entry
* [x] Tests (if applicable)

2023-01-05 15:34 UTC, nirinchev approved these changes
Looks reasonable to me

2023-01-05 15:34 UTC, nirinchev commented on Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/NestedClassWithoutPartialParent.diagnostics.cs
> +    "Message": "Class OuterClassNonPartial contains nested Realm class OuterClassNonPartial.NestedClassWithoutPartialParent and needs to be declared as partial.",
Now that we have the name of the parent, we probably don't need the full name of the child.

2023-01-06 12:41 UTC, nirinchev requested changes
Be sure to check the weaver tests as those failures seem relevant.

2023-01-06 14:59 UTC, papafe commented
This should be ready to merge. The CI errors seems to be unrelated

2023-01-09 11:17 UTC, LaPeste approved these changes
It generally makes sense to me.

2023-01-09 16:21 UTC, nirinchev approved these changes

2023-01-09 16:21 UTC, nirinchev commented on Tests/Realm.Tests/Database/AddOrUpdateTests.cs
Empty line

2023-01-10 12:10 UTC, merged