Find installation method for analytics
realm/realm-dotnet pull request #3204
Opened 2023-01-26 15:22 UTC by papafe

Fixes #3184

2023-01-27 11:15 UTC, papafe commented
I've timed it before. When the project is opened it takes about 1.8-2s to find the value, the following times about 0.3s

2023-01-30 11:16 UTC, LaPeste requested changes
Just a few nits on style but otherwise it looks good.

2023-01-30 11:16 UTC, LaPeste commented on Realm/Realm.UnityWeaver/UnityWeaver.cs
> +                        InstallationMethod = installMethod
```suggestion
                        InstallationMethod = _installMethodTask.Task.Result
```

2023-01-30 11:16 UTC, LaPeste commented on Realm/Realm.UnityWeaver/UnityWeaver.cs
> +                        break;
```suggestion                        
                        if (package.name == UnityPackageName)
                        {
                            var source = package.source;
                            installMethod = source switch
                            {
                                PackageSource.LocalTarball => "Manual",
                                PackageSource.Registry => "NPM",
                                _ => installMethod,
                            };

                            break;
                        }
```

2023-01-30 12:16 UTC, LaPeste commented on Realm/Realm.UnityWeaver/UnityWeaver.cs
> +                            installMethod = source switch
```suggestion
                            installMethod = package.source switch
```

2023-01-30 12:19 UTC, LaPeste approved these changes

2023-02-02 10:59 UTC, papafe commented
@LaPeste looks fine to me!

2023-02-02 11:01 UTC, merged