Update to new documentation URL
realm/realm-dotnet pull request #3568
Opened 2024-04-08 10:29 UTC by kneth

## Description

Fixes #

##  TODO

* [ ] Changelog entry
* [ ] Tests

2024-04-08 12:21 UTC, papafe approved these changes
Looks good! Congratulation on your first contribution 😁

2024-04-08 14:55 UTC, nirinchev reviewed
There's a bunch of API docs that also need to be updated. If you grep for `docs.mongodb.com` you can find those.

2024-04-10 09:07 UTC, papafe requested changes
Looks good, just a couple of comments

2024-04-10 09:07 UTC, papafe commented on Realm/Realm/Exceptions/Sync/ErrorCode.cs
> +    /// <seealso href="https://www.mongodb.com/docs/realm/sdk/dotnet/sync/client-reset#manual-recovery/">
```suggestion
    /// <seealso href="https://www.mongodb.com/docs/realm/sdk/dotnet/sync/client-reset#manual-recovery/"/>
```

2024-04-10 09:07 UTC, papafe commented on Docs/index.md
> +The documentation can be found at [https://www.mongodb.com/docs/atlas/d
I suppose there shouldn't be a newline here

2024-04-17 07:02 UTC, papafe approved these changes
Apart from one comment, I think it's ready to merge

2024-04-17 07:02 UTC, papafe commented on Realm/Realm/Exceptions/Sync/ErrorCode.cs
> +    /// <seealso href="https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/sync/client-reset/#manual-recovery/">
```suggestion
    /// <seealso href="https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/sync/client-reset/#manual-recovery/"/>
```

2024-04-22 14:49 UTC, merged